// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GameCalculatorLibrary.Models
{

    [Table("Game")]
    public partial class Game
    {
        [Key]
        [Column("ID")]
        public int ID { get; set; }
        [StringLength(50)]
        public string GameName { get; set; }
        public int? MinutesPerEnergy { get; set; }
        public int? MaximumEnergyCap { get; set; }
    }
}